### PR TITLE
Docker Compose v2 updates and more flexible usage across the board

### PR DESCRIPTION
**Pull request by rawkode**
This is obviously a pretty large update - hopefully you see most of the changes as positive 👍

### CODE REVIEW

**Comment by mitchellvanw** [comment]
Looks great, thanks!

I also don't mind the changes. Just have one question. What's the reason for removing the `my_app` container?

**Comment by rawkode** [comment]
It didn't provide any purpose? It only housed the code, which is no different from mounting the code into the other containers.

We can use a Docker volume to house all the logs / cache and avoid them being rewritten back to the host machine - much better performance on OSX/Windows

**Comment by mitchellvanw** [comment]
Alright, cool. It seems to ignore the ports or something, though. For some reason nginx is running on port `32805`, instead of `80`

**Comment by rawkode** [comment]
When only one value is provided, it means expose this on any port, and uses one at random. This allows people to be working on multiple projects at the same time.

```
ports:
    - 80
```

**Comment by mitchellvanw** [comment]
Ah, didn't know this. I've merged your code in master, manually, because of some changes. Unfortunately GitHub doesn't recognize this.

But thanks for the additions!

**Comment by rawkode** [comment]
Why manually?

**Comment by mitchellvanw** [comment]
I made some changes and GitHub was complaining there were merge conflicts that had to be fixed by hand.

**Comment by rawkode** [comment]
I would have been happy to rebase my work 👎

**Pull request closed without merging**
